name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})

    strategy:
      matrix:
        include:
          - elixir: 1.14.5
            otp: 24.3

          - elixir: 1.15.4
            otp: 25.3

          - elixir: 1.16.3
            otp: 26.2

          - elixir: 1.17.2
            otp: 27.0

    runs-on: ubuntu-latest

    steps:
      - name: Install inotify-tools
        run: |
          sudo apt update
          sudo apt install -y inotify-tools
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Remove compiled application files
        run: mix clean

      - name: Compile dependencies
        run: mix compile
        # if: ${{ !matrix.lint }}
        env:
          MIX_ENV: test

      - name: Compile & lint dependencies
        run: mix compile --warnings-as-errors
        # if: ${{ matrix.lint }}
        env:
          MIX_ENV: test

      - name: Check if formatted
        run: mix format --check-formatted
        # if: ${{ matrix.lint }}
        env:
          MIX_ENV: test

      - name: Run tests
        run: mix test
